# Generated by Django 3.0.9 on 2020-08-10 15:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
